package main

import (
	"errors"
	"fmt"
	"os"
	"slices"
	"strings"
)

type CLIConfig interface {
	ToNonInputOptions() []string                         // Retrieves literal list of acceptable enumerated options
	FromNonInputList(flags []string) error               // Reads list of options and configures CLIConfig accordingly
	FromInteractiveMap(flag_map map[string]string) error // Reads option and its value and to set CLIConfig
	ApplyCLIInputs(noninput_vals []string, interactive_map map[string]string) error
}

// Struct with configuration options for tihs program
type RefreshCLI struct {
	Path               string
	TrackedFilesAction string
	Propagate          bool
	ExemptionsSrc      string
	Pull               bool
	SkipRecycle        bool
}

// Function to instantiate CLIConfig with program-specific defaults
func DefaultRefreshCLI() RefreshCLI {
	return RefreshCLI{Path: ".", TrackedFilesAction: "null", Propagate: false, ExemptionsSrc: "refresh", Pull: false}
}

// Generate literal containing valid enumerated program options/flags (options not taking values)
func (r *RefreshCLI) ToNonInputOptions() []string {
	output := []string{"--propagate", "-p", "--pull", "--no-pull", "-gp", "-ngp", "--skip", "-s"}
	return output
}

// Takelist of strings and set CLIConfig fields accoridngly.
// Acceptable values should be the same set of values generated by ToNonInputOptions.
// Any other values should return an error with the unrecognized value
func (r *RefreshCLI) FromNonInputList(flags []string) error {
	for _, flag := range flags {
		switch flag {
		case "--propagate", "-p":
			r.Propagate = true
		case "--pull", "-gp":
			r.Pull = true
		case "--no-pull", "-ngp":
			r.Pull = false
		case "--skip", "-s":
			r.SkipRecycle = true
		default:
			return errors.New(fmt.Sprintln("Flag not recognized: ", flag))
		}
	}
	return nil
}

func (r *RefreshCLI) FindRefreshTargets() Result[[]string] {
	if r.Propagate {
		nested_dirs, _ := GetNestedDirs(r.Path)
		r_git_repos := CheckGitDirs(nested_dirs)
		return *r_git_repos.Context("Error while propagating git refresh")
	} else {
		return Ok([]string{r.Path})
	}
}

func (r *RefreshCLI) CloneWNewPath(new_path string) RefreshCLI {
	return RefreshCLI{
		Path:               new_path,
		TrackedFilesAction: r.TrackedFilesAction,
		Propagate:          r.Propagate,
		ExemptionsSrc:      r.ExemptionsSrc,
		Pull:               r.Pull,
		SkipRecycle:        r.SkipRecycle,
	}
}

// Set RefreshCLI mode for handling deltas to git-tracked files.
func deltaParse(s string) (string, error) {
	opt_mapping := map[string]string{
		"stash":   "stash",
		"s":       "stash",
		"restore": "restore",
		"r":       "restore",
		"null":    "null",
		"n":       "null",
	}
	out_val, found := opt_mapping[s]
	if !found {
		return "", errors.New(fmt.Sprintln("Unrecognized value for delta option: ", s))
	}
	return out_val, nil
}

func parseDelta(s string) Result[string] {
	res, err := deltaParse(s)
	return Result[string]{inner: res, err: err}
}

// Set RefreshCLI mode for finding paths exempt from recycling by git refresh.
func exemptsParse(s string) (string, error) {
	opt_mapping := map[string]string{
		"git-refresh": "refresh",
		"r":           "refresh",
		"git-ignore":  "ignore",
		"i":           "ignore",
	}
	out_val, found := opt_mapping[s]
	if !found {
		return "", errors.New(fmt.Sprintln("Unrecognized value for exemptions option: ", s))
	}
	return out_val, nil
}

func parseExempts(s string) Result[string] {
	res, err := exemptsParse(s)
	return Result[string]{inner: res, err: err}
}

// Take options (map keys) and their values and configure CLIConfig accordingly
// Each implementation will rely on unique parsing functions based on each field for which parsing is necessary
func (r *RefreshCLI) FromInteractiveMap(flag_map map[string]string) error {
	for opt, opt_val := range flag_map {
		switch opt {
		case "--delta", "-d":
			delta_val, delta_err := deltaParse(opt_val)
			if delta_err != nil {
				return delta_err
			}
			r.TrackedFilesAction = delta_val
		case "--exemptions", "-e":
			exempt_val, exempt_err := exemptsParse(opt_val)
			if exempt_err != nil {
				return exempt_err
			}
			r.ExemptionsSrc = exempt_val
		case "--path":
			if len(opt_val) == 0 {
				r.Path = "."
			} else {
				r.Path = opt_val
			}
		default:
			return errors.New(fmt.Sprintln("Flag not recognized: ", opt))
		}
	}
	return nil
}

func ParseArgs(args []string, config CLIConfig) ([]string, map[string]string, error) {
	noninput_flags := config.ToNonInputOptions()
	noninput_vals := []string{}
	//interactive_flags := (*config).ToInteractiveOptions()
	interactive_map := map[string]string{"--path": ""}
	remainders := []string{}

	// Take flags not taking inputs and extract
	for _, arg := range args {
		if slices.Contains(noninput_flags, arg) {
			noninput_vals = append(noninput_vals, arg)
		} else {
			remainders = append(remainders, arg)
		}
	}

	// Split any options on = which were concatenated with their value
	split_remainders := []string{}
	for _, arg := range remainders {
		if strings.Contains(arg, "=") {
			pairs := strings.Split(arg, "=")
			split_remainders = append(split_remainders, pairs[0], pairs[1])
		} else {
			split_remainders = append(split_remainders, arg)
		}
	}

	interactive_map, interact_parse_err := ParseInteractiveOptionsWPath(split_remainders, interactive_map)
	if interact_parse_err != nil {
		return nil, nil, fmt.Errorf("Error when parsing options w/ values: %v", interact_parse_err)
	}

	return noninput_vals, interactive_map, nil
}

func ParseInteractiveOptionsWPath(args []string, opt_map map[string]string) (map[string]string, error) {
	args_len := len(args)
	if args_len == 0 {
		return opt_map, nil
	}
	// If args are odd
	if args_len%2 == 1 {
		dashed, undashed := DashedVsUndashed(args)
		if undashed != dashed+1 {
			return nil, fmt.Errorf(
				"Found %v dashed and %v undashed args, undashed should be 0 or 1 more",
				dashed,
				undashed,
			)
		}
		new_arr := []string{}
		dash_state := true
		for _, elt := range args {
			if (dash_state && strings.HasPrefix(elt, "-")) || (!dash_state && !strings.HasPrefix(elt, "-")) {
				new_arr = append(new_arr, elt)
				dash_state = !dash_state
			} else if dash_state && !strings.HasPrefix(elt, "-") {
				new_arr = append(new_arr, "--path", elt)
			} else {
				return nil, errors.New("While parsing args, found option (- prefix) when expecting value")
			}
		}
		args = new_arr
	}
	dash_check, undashed_check := DashedVsUndashed(args)
	if dash_check != undashed_check {
		return nil, fmt.Errorf("Expected one value per opt, found %v opts and %v values", dash_check, undashed_check)
	}
	if !AlternatingDashes(args) {
		return nil, fmt.Errorf("Args not provided in option-value pairs")
	}
	current_opt := ""
	for _, elt := range args {
		if strings.HasPrefix(elt, "-") {
			current_opt = elt
		} else {
			opt_map[current_opt] = elt
			current_opt = ""
		}
	}
	return opt_map, nil
}

func DashedVsUndashed(strs []string) (int, int) {
	dashed := 0
	undashed := 0
	for _, elt := range strs {
		if strings.HasPrefix(elt, "-") {
			dashed += 1
		} else {
			undashed += 1
		}
	}
	return dashed, undashed
}

func AlternatingDashes(strs []string) bool {
	dashed := true
	for _, elt := range strs {
		if (dashed && strings.HasPrefix(elt, "-")) || (!dashed && !strings.HasPrefix(elt, "-")) {
			dashed = !dashed
		} else {
			return false
		}
	}
	return true
}

func (c *RefreshCLI) ApplyCLIInputs(noninput_vals []string, interactive_map map[string]string) error {
	parse_noninputs_err := c.FromNonInputList(noninput_vals)
	if parse_noninputs_err != nil {
		return parse_noninputs_err
	}
	parse_interactive_err := c.FromInteractiveMap(interactive_map)
	return parse_interactive_err
}

// TrackedFilesAction should be in ["stash", "restore", "null"] (default as stash)
// Pull, Propagate should be T/F (defaults as T and F, respectively)
// ExemptionSrc should be ["(git)refresh", "(git)ignore"] (default as refresh)
// Path should be interpretable as . or path (default as .)

func GetCLIArgs() []string {
	args := os.Args[1:]
	return args
}

func GetGitRefreshConfig() (*RefreshCLI, error) {
	args := GetCLIArgs()
	program_config := DefaultRefreshCLI()
	// NOTE: Consider adding -v verbal mode
	non_input_opts, interactive_map, parse_error := ParseArgs(args, &program_config)
	if parse_error != nil {
		// TODO: Add logging on early returns
		return nil, parse_error
	}
	apply_opts_error := (&program_config).ApplyCLIInputs(non_input_opts, interactive_map)
	if apply_opts_error != nil {
		fmt.Printf("Error applying: %v\n", apply_opts_error)
		fmt.Println("noninputs: ", non_input_opts)
		fmt.Printf("interactive map: %v\n", interactive_map)
		return nil, apply_opts_error
	}

	if program_config.Path == "." {
		var cwd_err error
		program_config.Path, cwd_err = os.Getwd()
		if cwd_err != nil {
			return nil, cwd_err
		}
	}
	return &program_config, nil
}

func GetConfig() Result[*RefreshCLI] {
	config, err := GetGitRefreshConfig()
	return Result[*RefreshCLI]{inner: config, err: err}
}
