package main

import (
	"errors"
	"fmt"
	"os"
	"slices"
	"strings"
)

type CLIConfig interface {
	ToNonInputOptions() []string                         // Retrieves literal list of acceptable enumerated options
	FromNonInputList(flags []string) error               // Reads list of options and configures CLIConfig accordingly
	FromInteractiveMap(flag_map map[string]string) error // Reads option and its value and to set CLIConfig
	ApplyCLIInputs(noninput_vals []string, interactive_map map[string]string) error
}

// Struct with configuration options for tihs program
type RefreshCLI struct {
	Path               string
	TrackedFilesAction string
	Propagate          bool
	ExemptionsSrc      string
	Pull               bool
}

// Function to instantiate CLIConfig with program-specific defaults
func DefaultRefreshCLI() RefreshCLI {
	return RefreshCLI{Path: ".", TrackedFilesAction: "null", Propagate: false, ExemptionsSrc: "refresh", Pull: false}
}

// Generate literal containing valid enumerated program options/flags (options not taking values)
func (r *RefreshCLI) ToNonInputOptions() []string {
	output := []string{"--propagate", "-p", "--pull", "--no-pull", "-gp", "-ngp"}
	return output
}

// Takelist of strings and set CLIConfig fields accoridngly.
// Acceptable values should be the same set of values generated by ToNonInputOptions.
// Any other values should return an error with the unrecognized value
func (r *RefreshCLI) FromNonInputList(flags []string) error {
	for _, flag := range flags {
		switch flag {
		case "--propagate", "-p":
			r.Propagate = true
		case "--pull", "-gp":
			r.Pull = true
		case "--no-pull", "-ngp":
			r.Pull = false
		default:
			return errors.New(fmt.Sprintln("Flag not recognized: ", flag))
		}
	}
	return nil
}

// Set RefreshCLI mode for handling deltas to git-tracked files.
func deltaParse(s string) (string, error) {
	opt_mapping := map[string]string{
		"stash":   "stash",
		"s":       "stash",
		"restore": "restore",
		"r":       "restore",
		"null":    "null",
		"n":       "null",
	}
	out_val, found := opt_mapping[s]
	if !found {
		return "", errors.New(fmt.Sprintln("Unrecognized value for delta option: ", s))
	}
	return out_val, nil
}

// Set RefreshCLI mode for finding paths exempt from recycling by git refresh.
func exemptsParse(s string) (string, error) {
	opt_mapping := map[string]string{
		"git-refresh": "refresh",
		"r":           "refresh",
		"git-ignore":  "ignore",
		"i":           "ignore",
	}
	out_val, found := opt_mapping[s]
	if !found {
		return "", errors.New(fmt.Sprintln("Unrecognized value for exemptions option: ", s))
	}
	return out_val, nil
}

// Take options (map keys) and their values and configure CLIConfig accordingly
// Each implementation will rely on unique parsing functions based on each field for which parsing is necessary
func (r *RefreshCLI) FromInteractiveMap(flag_map map[string]string) error {
	for opt, opt_val := range flag_map {
		switch opt {
		case "--delta", "-d":
			delta_val, delta_err := deltaParse(opt_val)
			if delta_err != nil {
				return delta_err
			}
			r.TrackedFilesAction = delta_val
		case "--exemptions", "-e":
			exempt_val, exempt_err := exemptsParse(opt_val)
			if exempt_err != nil {
				return exempt_err
			}
			r.ExemptionsSrc = exempt_val
		default:
			return errors.New(fmt.Sprintln("Flag not recognized: ", opt))
		}
	}
	return nil
}

func ParseArgs(args []string, config CLIConfig) ([]string, map[string]string, error) {
	noninput_flags := config.ToNonInputOptions()
	noninput_vals := []string{}
	//interactive_flags := (*config).ToInteractiveOptions()
	interactive_map := map[string]string{"path": ""}
	remainders := []string{}

	// Take flags noot taking inputs and extract
	for _, arg := range args {
		if slices.Contains(noninput_flags, arg) {
			noninput_vals = append(noninput_vals, arg)
		} else {
			remainders = append(remainders, arg)
		}
	}

	fmt.Println("Noninputs: ", noninput_vals)

	// Split any options on = which were concatenated with their value
	split_remainders := []string{}
	for _, arg := range remainders {
		if strings.Contains(arg, "=") {
			pairs := strings.Split(arg, "=")
			split_remainders = append(split_remainders, pairs[0], pairs[1])
		} else {
			split_remainders = append(split_remainders, arg)
		}
	}

	// Now apply unified sliding window method for reading input pairs
	used_options := []string{}
	fmt.Println(split_remainders)
	for i := 0; i < len(split_remainders)-1; i++ {
		if strings.HasPrefix(split_remainders[i], "-") &&
			!slices.Contains(used_options, split_remainders[i+1]) &&
			!slices.Contains(used_options, split_remainders[i]) {
			interactive_map[split_remainders[i]] = split_remainders[i+1]
			used_options = append(used_options, split_remainders[i], split_remainders[i+1])
		}
	}

	// In this case, exactly 1 should be unused (the path value)
	if len(split_remainders) == len(used_options)+1 {
		for _, val := range split_remainders {
			if !slices.Contains(used_options, val) {
				interactive_map["path"] = val
				break
			}
		}
		path := interactive_map["path"]
		if len(path) <= 0 {
			return nil, nil, errors.New(fmt.Sprintf("Issue finding unambigious path term in subset %v of cli args %v\n", split_remainders, args))
		}
	} else if (len(split_remainders) > len(used_options)+1) || (len(split_remainders) < len(used_options)) {
		return nil, nil, errors.New(fmt.Sprintf("Issue finding unambigious path term in subset %v of cli args %v\n", split_remainders, args))
	}

	return noninput_vals, interactive_map, nil
}

func (c *RefreshCLI) ApplyCLIInputs(noninput_vals []string, interactive_map map[string]string) error {
	parse_noninputs_err := c.FromNonInputList(noninput_vals)
	if parse_noninputs_err != nil {
		return parse_noninputs_err
	}
	parse_interactive_err := c.FromInteractiveMap(interactive_map)
	return parse_interactive_err
}

// TrackedFilesAction should be in ["stash", "restore", "null"] (default as stash)
// Pull, Propagate should be T/F (defualtsa as T and F, respectively)
// ExemptionSrc should be ["(git)refresh", "(git)ignore"] (default as refresh)
// Path should be interpretable as . or path (default as .)

func GetCLIArgs() []string {
	args := os.Args[1:]
	fmt.Println("cli inputs: ", args)
	return args
}

// TODO: Wrap all up into GetGitRefreshConfig() CLIConfig to get configuration at top level
// TODO: Replace slice and maps equals checks with reflect.DeepEquals or some equivalent
func GetGitRefreshConfig() (*RefreshCLI, error) {
	args := GetCLIArgs()
	program_config := DefaultRefreshCLI()
	// NOTE: Consider adding -v verbal mode
	non_input_opts, interactive_map, parse_error := ParseArgs(args, &program_config)
	if parse_error != nil {
		// TODO: Add logging on early returns
		return nil, parse_error
	}
	apply_opts_error := (&program_config).ApplyCLIInputs(non_input_opts, interactive_map)
	if apply_opts_error != nil {
		return nil, apply_opts_error
	}
	return &program_config, nil

}
